// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb4SQIf7TU0LmkDZg0VWxOZt2lqJN00Q8',
    appId: '1:1000218679640:web:2b85dd5fffc88754e1ad2d',
    messagingSenderId: '1000218679640',
    projectId: 'dip-ee018',
    authDomain: 'dip-ee018.firebaseapp.com',
    databaseURL: 'https://dip-ee018-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dip-ee018.appspot.com',
    measurementId: 'G-921RLFKHS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChbM81w4ZPP6zW8dpB5hpf4lI5loADj-Y',
    appId: '1:1000218679640:android:3d77b54c2a4b634be1ad2d',
    messagingSenderId: '1000218679640',
    projectId: 'dip-ee018',
    databaseURL: 'https://dip-ee018-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dip-ee018.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxYfdKOfKS4n7eWl1olX6na70bYGtmaxc',
    appId: '1:1000218679640:ios:1c2d5251abf7e205e1ad2d',
    messagingSenderId: '1000218679640',
    projectId: 'dip-ee018',
    databaseURL: 'https://dip-ee018-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dip-ee018.appspot.com',
    iosClientId: '1000218679640-t0954h63kmv5fuif4bssrhirvelo3l5p.apps.googleusercontent.com',
    iosBundleId: 'com.dip.irentApp',
  );
}
