export const utensils = [
  { name: "Non-Stick Pan" },
  { name: "Cast Iron Skillet" },
  { name: "Saucepan" },
  { name: "Dutch Oven" },
  { name: "Grill Pan" },
  { name: "Wok" },
  { name: "Baking Sheet" },
  { name: "Roasting Pan" },
  { name: "Muffin Tin" },
  { name: "Cake Pan" },
  { name: "Loaf Pan" },
  { name: "Pie Dish" },
  { name: "Casserole Dish" },
  { name: "Frying Pan" },
  { name: "Stock Pot" },
  { name: "Sauté Pan" },
  { name: "Pressure Cooker" },
  { name: "Slow Cooker" },
  { name: "Rice Cooker" },
  { name: "Mandoline Slicer" },
  { name: "Box Grater" },
  { name: "Food Processor" },
  { name: "Blender" },
  { name: "Immersion Blender" },
  { name: "Stand Mixer" },
  { name: "Hand Mixer" },
  { name: "Pastry Blender" },
  { name: "Rolling Pin" },
  { name: "Basting Brush" },
  { name: "Silicone Spatula" },
  { name: "Wooden Spoon" },
  { name: "Slotted Spoon" },
  { name: "Soup Ladle" },
  { name: "Pasta Server" },
  { name: "Tongs" },
  { name: "Measuring Cups" },
  { name: "Measuring Spoons" },
  { name: "Kitchen Scale" },
  { name: "Thermometer" },
  { name: "Oven Mitts" },
  { name: "Pot Holders" },
  { name: "Apron" },
  { name: "Chef's Knife" },
  { name: "Paring Knife" },
  { name: "Bread Knife" },
  { name: "Utility Knife" },
  { name: "Serrated Knife" },
  { name: "Knife Sharpener" },
  { name: "Knife Block" },
  { name: "Cutting Board" },
  { name: "Peeler" },
  { name: "Garlic Press" },
  { name: "Can Opener" },
  { name: "Bottle Opener" },
  { name: "Wine Opener" },
  { name: "Corkscrew" },
  { name: "Mortar and Pestle" },
  { name: "Spice Grinder" },
  { name: "Salt Cellar" },
  { name: "Pepper Mill" },
  { name: "Butter Dish" },
  { name: "Sugar Bowl" },
  { name: "Creamer" },
  { name: "Teapot" },
  { name: "Coffee Maker" },
  { name: "French Press" },
  { name: "Espresso Machine" },
  { name: "Tea Kettle" },
  { name: "Toaster" },
  { name: "Toaster Oven" },
  { name: "Microwave" },
  { name: "Refrigerator" },
  { name: "Freezer" },
  { name: "Dishwasher" },
  { name: "Cheese Grater" },
  { name: "Citrus Juicer" },
  { name: "Garlic Press" },
  { name: "Mortar and Pestle" },
  { name: "Potato Ricer" },
  { name: "Vegetable Peeler" },
  { name: "Apple Corer" },
  { name: "Egg Slicer" },
  { name: "Can Opener" },
  { name: "Kitchen Shears" },
  { name: "Bamboo Skewers" },
  { name: "Pastry Brush" },
  { name: "Rolling Dough Cutter" },
  { name: "Cake Stand" },
  { name: "Mandolin" },
  { name: "Melon Baller" },
  { name: "Fish Spatula" },
  { name: "Sushi Mat" },
  { name: "Tortilla Press" },
  { name: "Pizza Stone" },
  { name: "Smoker Box" },
  { name: "BBQ Gloves" },
  { name: "Meat Thermometer" },
  { name: "Meat Tenderizer" },
  { name: "Poultry Shears" },
  { name: "Gravy Separator" },
  { name: "Salad Spinner" },
  { name: "Ice Cream Scoop" },
  { name: "Soup Strainer" },
  { name: "Slotted Spatula" },
  { name: "Bread Box" },
  { name: "Vegetable Brush" },
  { name: "Wine Aerator" },
  { name: "Bottle Stopper" },
  { name: "Oil Mister" },
  { name: "Popcorn Maker" },
  { name: "Cookie Cutters" },
  { name: "Piping Bags" },
  { name: "Silicone Baking Mats" },
  { name: "Cake Tester" },
  { name: "Egg Separator" },
  { name: "Candy Thermometer" },
  { name: "Chocolate Melting Pot" },
  { name: "Pastry Wheel" },
  { name: "Bread Knife" },
  { name: "Butcher Knife" },
  { name: "Cleaver" },
  { name: "Carving Knife" },
  { name: "Filet Knife" },
  { name: "Bread Lame" },
  { name: "Kitchen Torch" },
  { name: "Cheese Knife" },
  { name: "Oyster Knife" },
  { name: "Lobster Cracker" },
  { name: "Seafood Scissors" },
  { name: "Vegetable Chopper" },
  { name: "Onion Goggles" },
  { name: "Egg Poacher" },
  { name: "Egg Cooker" },
  { name: "Popcorn Popper" },
  { name: "Electric Griddle" },
  { name: "Glass Bowl" },
  { name: "Mixer" },
  { name: "Food processor" },
  { name: "Panini Press" },
  { name: "Toaster Bags" },
  { name: "Electric Kettle" },
  { name: "Food Dehydrator" },
  { name: "Ice Cream Maker" },
  { name: "Yogurt Maker" },
  { name: "Canning Kit" },
  { name: "Food Mill" },
  { name: "Kitchen Timer" },
];

export const uniqueUtensils = Object.values(
  utensils.reduce((acc, curr) => {
    if (!acc[curr.name]) {
      acc[curr.name] = curr;
    }
    return acc;
  }, {})
);
